import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components/Header'
import { About } from '@/components/About'
import { Services } from '@/components/Services'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Barber Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" imageSrcSet="@/../public/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Services />
    </>
  )
}
